#=================================================
# https://github.com/qcgzxw/iplist
# Description: Update ip list using GitHub Actions
# Lisence: GNU Lesser General Public License v3.0
# Author: qcgzxw
# Blog: https://www.qcgzxw.com
#=================================================


name: Update Ip List

on:
  release:
    types: published
  push:
    branches: 
      - master
    paths:
      - '.config'

env:
  CONFIG_FILE: .config

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pull repository "iplist_action"
      uses: actions/checkout@v2
      with:
        repository: qcgzxw/iplist_action
        token: ${{ secrets.GIT_PAT }}


    - name: Pull repository "iplist"
      uses: actions/checkout@v2
      with:
        path: iplist
        persist-credentials: false
        fetch-depth: 0


    - name: Initialization environment
      run: |
        sudo -E apt-get -qq install python3-setuptools


    - name: Update ip list
      run: |
        [ -e iplist/$CONFIG_FILE ] && cp iplist/$CONFIG_FILE .config
        pip3 install wheel
        pip3 install -r requirements.txt
        python3 main.py


    - name: Commit files
      run: |
        cd iplist
        git config --local user.email "qcgzxw@qq.com"
        git config --local user.name "GitHub Action"
        git add *
        git commit -m "update ip list" -a


    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: update
        directory: iplist
        force: true
